name: Compile LaTeX Files

on:
  push:
    paths:
      - 'input/**/start.txt'
    branches:
      - main
    types:
      - added
  pull_request:
    paths:
      - 'input/**/start.txt'
    types:
      - added
  workflow_dispatch:

jobs:
  compile:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Create Output Directory
        run: mkdir -p output

      - name: Compile LaTeX Files using thomasweise/latex-thin
        uses: docker://thomasweise/latex-thin
        with:
          args: >
            sh -c "for file in input/*.tex; do pdflatex -interaction=nonstopmode -output-directory=output \"$file\"; done"

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Compiled LaTeX files
          file_pattern: '.'

      - name: Upload PDFs
        uses: actions/upload-artifact@v4
        with:
          name: compiled-pdfs
          path: output/*.pdf
